export const SIGN_OFF_RESULTS_REQUESTED_ACTION =
    "sign-off/SIGN_OFF_RESULTS_REQUESTED_ACTION";
export const SIGN_OFF_RESULTS_REQUEST_SUCCEEDED_ACTION =
    "sign-off/SIGN_OFF_RESULTS_REQUEST_SUCCEEDED_ACTION";

export const SIGN_OFF_SAVE_REQUESTED_ACTION =
    "sign-off/SIGN_OFF_SAVE_REQUESTED_ACTION";
export const SIGN_OFF_SAVE_REQUEST_SUCCEEDED_ACTION =
    "sign-off/SIGN_OFF_SAVE_REQUEST_SUCCEEDED_ACTION";
