export const SIGN_OFF_OVERVIEW_GROUPS_FETCH_REQUESTED_ACTION =
    "overview/GROUPS_FETCH_REQUESTED";

export const SIGN_OFF_OVERVIEW_GROUPS_FETCH_SUCCEEDED_ACTION =
    "overview/GROUPS_FETCH_SUCCEEDED";

export const SIGN_OFF_OVERVIEW_GROUPS_PAGE_FETCH_SUCCEEDED_ACTION =
    "overview/GROUPS_PAGE_FETCH_SUCCEEDED";

export const SIGN_OFF_OVERVIEW_RESULTS_FETCH_REQUESTED_ACTION =
    "overview/SIGN_OFF_RESULTS_FETCH_REQUESTED_ACTION";

export const SIGN_OFF_OVERVIEW_RESULTS_FETCH_SUCCEEDED_ACTION =
    "overview/SIGN_OFF_RESULTS_FETCH_SUCCEEDED_ACTION";

export const SIGN_OFF_OVERVIEW_FILTER_QUERY_ACTION =
    "search/sign-off/SIGN_OFF_OVERVIEW_FILTER_QUERY_ACTION";
export const SIGN_OFF_OVERVIEW_FILTER_SUCCEEDED_ACTION =
    "search/sign-off/SIGN_OFF_OVERVIEW_FILTER_SUCCEEDED_ACTION";
