image: richyrick/horus_builder

variables:
    POSTGRES_USER: horus
    POSTGRES_PASSWORD: horus

before_script:
    - /etc/init.d/postgresql start
    - (cd frontend/; yarn)
    
stages: 
    - build
    
build_backend:
    stage: build
    script:
        - (cd backend/; ./gradlew check)