image: richyrick/horus_builder

cache: 
    key: "ALL_SHARED_KEY"
    paths:
        - frontend/node_modules/
        - .gradle/caches
        - .gradle/wrapper

variables:
    POSTGRES_USER: horus
    POSTGRES_PASSWORD: horus

before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - /etc/init.d/postgresql start
    - (cd frontend/; yarn)
    
stages: 
    - check
    - test

lint_frontend:
    stage: check
    script:
        - (cd frontend/; yarn lint)

build_backend:
    stage: test
    script:
        - (cd backend/; ./gradlew check)
