export const LABEL_CREATE_ACTION = "courses/LABEL_CREATE_ACTION";
export const LABEL_CREATE_SUCCEEDED_ACTION = "courses/LABEL_CREATE_SUCCEEDED_ACTION";

export const LABEL_UPDATE_ACTION = "courses/LABEL_UPDATE_ACTION";
export const LABEL_UPDATE_SUCCEEDED_ACTION = "courses/LABEL_UPDATE_SUCCEEDED_ACTION";

export const LABEL_DELETE_ACTION = "courses/LABEL_DELETE_ACTION";
export const LABEL_DELETE_SUCCEEDED_ACTION = "courses/LABEL_DELETE_SUCCEEDED_ACTION";

export const LABEL_MAPPING_CREATE_ACTION = "courses/LABEL_MAPPING_CREATE_ACTION";
export const LABEL_MAPPING_CREATE_SUCCEEDED_ACTION = "courses/LABEL_MAPPING_CREATE_SUCCEEDED_ACTION";

export const LABEL_MAPPING_DELETE_ACTION = "courses/LABEL_MAPPING_DELETE_ACTION";
export const LABEL_MAPPING_DELETE_SUCCEEDED_ACTION = "courses/LABEL_MAPPING_DELETE_SUCCEEDED_ACTION";

export const LABEL_CSV_UPLOAD_ACTION = "courses/LABEL_CSV_UPLOAD_ACTION";
export const LABEL_CSV_UPLOAD_SUCCEEDED = "courses/LABEL_CSV_UPLOAD_SUCCEEDED";
