export const TOKEN_SUBMITTED_ACTION = "canvas-settings/TOKEN_SUBMITTED_ACTION";
export const TOKEN_SUBMIT_SUCCEEEDED_ACTION = "canvas-settings/TOKEN_SUBMIT_SUCCEEDED_ACTION";
export const CANVAS_COURSES_REQUESTED_ACTION = "canvas-settings/CANVAS_COURSES_REQUESTED_ACTION";
export const CANVAS_COURSES_REQUEST_SUCCEEDED_ACTION = "canvas-settings/CANVAS_COURSES_REQUEST_SUCCEEDED_ACTION";
export const IMPORT_CANVAS_COURSE_REQUESTED_ACTION = "canvas-settings/IMPORT_CANVAS_COURSE_REQUESTED_ACTION";
export const CHECK_TOKEN_AND_REDIRECT_IMPORT_ACTION = "canvas-settings/CHECK_TOKEN_AND_REDIRECT_IMPORT_ACTION";
export const CHECK_TOKEN_AND_REDIRECT_TOKEN_ACTION = "canvas-settings/CHECK_TOKEN_AND_REDIRECT_TOKEN_ACTION";
export const IMPORT_CANVAS_COURSE_FINISHED_ACTION = "canvas-settings/IMPORT_CANVAS_COURSE_FINISHED_ACTION";
