export const TOKEN_SUBMITTED_ACTION = "canvas-settings/TOKEN_SUBMITTED_ACTION";
export const TOKEN_SUBMIT_SUCCEEEDED_ACTION =
    "canvas-settings/TOKEN_SUBMIT_SUCCEEDED_ACTION";

export const CANVAS_COURSES_REQUESTED_ACTION =
    "canvas-settings/CANVAS_COURSES_REQUESTED_ACTION";
export const CANVAS_COURSES_REQUEST_SUCCEEDED_ACTION =
    "canvas-settings/CANVAS_COURSES_REQUEST_SUCCEEDED_ACTION";

export const IMPORT_CANVAS_COURSE_REQUESTED_ACTION =
    "canvas-settings/IMPORT_CANVAS_COURSE_REQUESTED_ACTION";
export const IMPORT_CANVAS_COURSE_FINISHED_ACTION =
    "canvas-settings/IMPORT_CANVAS_COURSE_FINISHED_ACTION";

export const CHECK_TOKEN_AND_REDIRECT_IMPORT_ACTION =
    "canvas-settings/CHECK_TOKEN_AND_REDIRECT_IMPORT_ACTION";
export const CHECK_TOKEN_AND_REDIRECT_TOKEN_ACTION =
    "canvas-settings/CHECK_TOKEN_AND_REDIRECT_TOKEN_ACTION";

export const CANVAS_REFRESH_SETS_LIST_REQUESTED_ACTION =
    "canvas-settings/CANVAS_REFRESH_SETS_LIST_REQUESTED_ACTION";
export const CANVAS_REFRESH_SETS_LIST_REQUEST_SUCCEEDED_ACTION =
    "canvas-settings/CANVAS_REFRESH_SETS_LIST_REQUEST_SUCCEEDED_ACTION";

export const CANVAS_REFRESH_SET_REQUESTED_ACTION =
    "canvas-settings/CANVAS_REFRESH_SET_REQUESTED_ACTION";
export const CANVAS_REFRESH_SET_REQUEST_SUCCEEDED_ACTION =
    "canvas-settings/CANVAS_REFRESH_SET_REQUEST_SUCCEEDED_ACTION";

export const CANVAS_IMPORT_GROUP_SET_REQUESTED_ACTION =
    "canvas/CANVAS_IMPORT_GROUP_SET_REQUESTED_ACTION";
export const CANVAS_IMPORT_GROUP_SET_REQUEST_SUCCEEDED_ACTION =
    "canvas/CANVAS_IMPORT_GROUP_SET_REQUEST_SUCCEEDED";

export const CANVAS_REFRESH_PARTICIPANTS_REQUESTED_ACTION =
    "canvas-settings/CANVAS_REFRESH_PARTICIPANTS_REQUESTED_ACTION";
export const CANVAS_REFRESH_PARTICIPANTS_REQUEST_SUCCEEDED_ACTION =
    "canvas-settings/CANVAS_REFRESH_PARTICIPANTS_REQUEST_SUCCEEDED_ACTION";

export const CANVAS_REFRESH_COURSE_REQUESTED_ACTION =
    "canvas-settings/CANVAS_REFRESH_COURSE_REQUESTED_ACTION";
export const CANVAS_REFRESH_COURSE_REQUEST_SUCCEEDED_ACTION =
    "canvas-settings/CANVAS_REFRESH_COURSE_REQUEST_SUCCEEDED_ACTION";
