export const SET_LOGIN_REDIRECT_REQUESTED_ACTION = "auth/LOGIN_REDIRECT" 
export const LOGIN_REQUESTED_ACTION = "auth/LOGIN_REQUESTED";
export const LOGIN_SUCCEEDED_ACTION = "auth/LOGIN_SUCCEEDED";
export const LOGIN_FAILED_ACTION = "auth/LOGIN_FAILED";

export const LOGOUT_REQUESTED_ACTION = "auth/LOGOUT_REQUESTED";
export const LOGOUT_COMPLETED_ACTION = "auth/LOGOUT_COMPLETED";

export const LOAD_AUTHENTICATION_REQUESTED_ACTION = "auth/LOAD_AUTHENTICATION";