export const ASSIGNMENT_SET_DTO_BRIEFS_FETCH_REQUESTED_ACTION =
    "courses/assignments/ASSIGNMENT_SET_DTO_BRIEFS_FETCH_REQUESTED";

export const ASSIGNMENT_SET_DTO_BRIEFS_FETCH_SUCCEEDED_ACTION =
    "courses/assignments/ASSIGNMENT_SET_DTO_BRIEFS_FETCH_SUCCEEDED";

export const ASSIGNMENT_SET_DTO_BRIEFS_FETCH_FAILED_ACTION =
    "courses/assignments/ASSIGNMENT_SET_DTO_BRIEFS_FETCH_FAILED";

export const ASSIGNMENT_GROUP_SETS_MAPPING_DTO_FETCH_REQUESTED_ACTION =
    "courses/assignments/ASSIGNMENT_GROUP_SETS_MAPPING_DTO_FETCH_REQUESTED_ACTION";

export const ASSIGNMENT_GROUP_SETS_MAPPING_DTO_FETCH_SUCCEEDED_ACTION =
    "courses/assignments/ASSIGNMENT_GROUP_SETS_MAPPING_DTO_FETCH_SUCCEEDED_ACTION";

export const ASSIGNMENT_GROUP_SETS_MAPPING_DTO_FETCH_FAILED_ACTION =
    "courses/assignments/ASSIGNMENT_GROUP_SETS_MAPPING_DTO_FETCH_FAILED_ACTION";
