export const ASSIGNMENT_SETS_FETCH_REQUESTED_ACTION =
    "courses/assignments/ASSIGNMENT_SETS_FETCH_REQUESTED_ACTION";

export const ASSIGNMENT_SETS_FETCH_SUCCEEDED_ACTION =
    "courses/assignments/ASSIGNMENT_SETS_FETCH_SUCCEEDED_ACTION";

export const ASSIGNMENT_GROUP_SETS_MAPPINGS_FETCH_REQUESTED_ACTION =
    "courses/assignments/ASSIGNMENT_GROUP_SETS_MAPPING_FETCH_REQUESTED_ACTION";

export const ASSIGNMENT_GROUP_SETS_MAPPINGS_FETCH_SUCCEEDED_ACTION =
    "courses/assignments/ASSIGNMENT_GROUP_SETS_MAPPING_FETCH_SUCCEEDED_ACTION";

export const ASSIGNMENT_SET_FETCH_REQUESTED_ACTION =
    "courses/assignments/ASSIGNMENT_SET_FETCH_REQUESTED_ACTION";

export const ASSIGNMENT_SET_FETCH_SUCCEEDED_ACTION =
    "courses/assignments/ASSIGNMENT_SET_FETCH_SUCCEEDED_ACTION";

export const ASSIGNMENT_SET_UPDATE_REQUESTED_ACTION =
    "courses/assignments/ASSIGNMENT_SET_UPDATE_REQUESTED";

export const ASSIGNMENT_SET_UPDATE_REQUEST_SUCCEEDED_ACTION =
    "courses/assignments/ASSIGNMENT_SET_UPDATE_REQUEST_SUCCEEDED_ACTION";

export const ASSIGNMENT_SET_CREATE_REQUESTED_ACTION =
    "courses/assignments/ASSIGNMENT_SET_CREATE_REQUESTED_ACTION";

export const ASSIGNMENT_SET_CREATE_REQUEST_SUCCEEDED_ACTION =
    "courses/assignments/ASSIGNMENT_SET_CREATE_REQUEST_SUCCEEDED_ACTION";
