export const ASSIGNMENT_SETS_FETCH_REQUESTED_ACTION =
    "courses/assignments/ASSIGNMENT_SETS_FETCH_REQUESTED_ACTION";
export const ASSIGNMENT_SETS_FETCH_SUCCEEDED_ACTION =
    "courses/assignments/ASSIGNMENT_SETS_FETCH_SUCCEEDED_ACTION";

export const ASSIGNMENT_GROUP_SETS_MAPPINGS_FETCH_REQUESTED_ACTION =
    "courses/assignments/ASSIGNMENT_GROUP_SETS_MAPPING_FETCH_REQUESTED_ACTION";
export const ASSIGNMENT_GROUP_SETS_MAPPINGS_FETCH_SUCCEEDED_ACTION =
    "courses/assignments/ASSIGNMENT_GROUP_SETS_MAPPING_FETCH_SUCCEEDED_ACTION";

export const ASSIGNMENT_SET_FETCH_REQUESTED_ACTION =
    "courses/assignments/ASSIGNMENT_SET_FETCH_REQUESTED_ACTION";
export const ASSIGNMENT_SET_FETCH_SUCCEEDED_ACTION =
    "courses/assignments/ASSIGNMENT_SET_FETCH_SUCCEEDED_ACTION";

export const ASSIGNMENT_SET_UPDATE_REQUESTED_ACTION =
    "courses/assignments/ASSIGNMENT_SET_UPDATE_REQUESTED";
export const ASSIGNMENT_SET_UPDATE_REQUEST_SUCCEEDED_ACTION =
    "courses/assignments/ASSIGNMENT_SET_UPDATE_REQUEST_SUCCEEDED_ACTION";

export const ASSIGNMENT_SET_CREATE_REQUESTED_ACTION =
    "courses/assignments/ASSIGNMENT_SET_CREATE_REQUESTED_ACTION";
export const ASSIGNMENT_SET_CREATE_REQUEST_SUCCEEDED_ACTION =
    "courses/assignments/ASSIGNMENT_SET_CREATE_REQUEST_SUCCEEDED_ACTION";

export const ASSIGNMENTS_DELETE_CHECK_REQUESTED_ACTION =
    "assignments/ASSIGNMENTS_DELETE_CHECK_REQUESTED_ACTION";
export const ASSIGNMENTS_DELETE_CHECK_SUCCEEDED_ACTION =
    "assignments/ASSIGNMENTS_DELETE_CHECK_SUCCEEDED_ACTION";

export const ASSIGNMENT_SET_DELETE_REQUESTED_ACTION =
    "assignments/ASSIGNMENT_SET_DELETE_REQUESTED_ACTION";
export const ASSIGNMENT_SET_DELETE_REQUEST_SUCCEEDED_ACTION =
    "assignments/ASSIGNMENT_SET_DELETE_REQUEST_SUCCEEDED_ACTION";

export const RESET_DELETE_CHECK_ACTION =
    "assignments/RESET_DELETE_CHECK_ACTION";
