export const SUPP_ROLES_FETCH_REQUESTED_ACTION =
    "roles/SUPP_ROLES_FETCH_REQUESTED_ACTION";
export const SUPP_ROLES_FETCH_REQUEST_SUCCEEDED_ACTION =
    "roles/SUPP_ROLES_FETCH_REQUEST_SUCCEEDED_ACTION";

export const SUPP_ROLES_MAPPING_FETCH_REQUESTED_ACTION =
    "roles/SUPP_ROLES_MAPPING_FETCH_REQUESTED_ACTION";
export const SUPP_ROLES_MAPPING_FETCH_REQUEST_SUCCEEDED_ACTION =
    "roles/SUPP_ROLES_MAPPING_FETCH_REQUEST_SUCCEEDED_ACTION";

export const SUPP_ROLES_MAPPING_CREATE_ACTION =
    "roles/SUPP_ROLES_MAPPING_CREATE_ACTION";
export const SUPP_ROLES_MAPPING_CREATE_SUCCEEDED_ACTION =
    "roles/SUPP_ROLES_MAPPING_CREATE_SUCCEEDED_ACTION";

export const SUPP_ROLES_MAPPING_DELETE_ACTION =
    "roles/SUPP_ROLES_MAPPING_DELETE_ACTION";
export const SUPP_ROLES_MAPPING_DELETE_SUCCEEDED_ACTION =
    "roles/SUPP_ROLES_MAPPING_DELETE_SUCCEEDED_ACTION";
