INSERT INTO permission(name) VALUES ('COURSE_COMMENT_STAFFONLY/OWN/EDIT'), ('COURSE_COMMENT_STAFFONLY/OWN/DELETE'),
                                    ('COURSE_COMMENT_PUBLIC/OWN/EDIT'), ('COURSE_COMMENT_PUBLIC/OWN/DELETE');

INSERT INTO role_permission(role_id, permission_name)
VALUES (2, 'COURSE_COMMENT_STAFFONLY/OWN/EDIT'), (2, 'COURSE_COMMENT_STAFFONLY/OWN/DELETE'),
       (2, 'COURSE_COMMENT_PUBLIC/OWN/EDIT'), (2, 'COURSE_COMMENT_PUBLIC/OWN/DELETE'),
       (3, 'COURSE_COMMENT_STAFFONLY/OWN/EDIT'), (3, 'COURSE_COMMENT_STAFFONLY/OWN/DELETE'),
       (3, 'COURSE_COMMENT_PUBLIC/OWN/EDIT'), (3, 'COURSE_COMMENT_PUBLIC/OWN/DELETE');

DELETE FROM role_permission WHERE role_id = 3 AND permission_name LIKE 'COURSE_PARTICIPANT_LABEL_MAPPING/ANY/CREATE';
DELETE FROM role_permission WHERE role_id = 3 AND permission_name LIKE 'COURSE_PARTICIPANT_LABEL_MAPPING/ANY/DELETE';

DELETE FROM role_permission WHERE role_id = 3 AND permission_name LIKE 'COURSE_COMMENT_STAFFONLY/ANY/EDIT';
DELETE FROM role_permission WHERE role_id = 3 AND permission_name LIKE 'COURSE_COMMENT_PUBLIC/ANY/EDIT';
