export const PROJECTOR_POPUP_TIMEOUT = 4000;
export const HISTORY_SIZE = 5;

export const UPDATE_RECEIVED_ACTION = "queuing/UPDATE_RECEIVED_ACTION";

export const ACCEPT_REQUESTED_ACTION = "queing/ACCEPT_REQUESTED_ACTION";

export const ANNOUNCEMENT_CREATED_ACTION =
    "queuing/ANNOUNCEMENT_CREATED_ACTION";

export const QUEUE_CREATED_ACTION = "queuing/QUEUE_CREATED_ACTION";

export const QUEUE_EDIT_REQUESTED_ACTION =
    "queuing/QUEUE_EDIT_REQUESTED_ACTION";
export const QUEUE_EDIT_REQUEST_SUCCEEDED_ACTION =
    "queuing/QUEUE_EDIT_REQUEST_SUCCEEDED_ACTION";

export const DEQUEUE_REQUESTED_ACTION = "queuing/DEQUEUE_REQUESTED_ACTION";

export const QUEUE_CHANGED_ACTION = "queuing/QUEUE_CHANGED_ACTION";

export const ENTER_QUEUE_ACTION = "queuing/ENTER_QUEUE_ACTION";

export const REMIND_REQUESTED_ACTION = "queuing/REMIND_REQUESTED_ACTION";

export const ANNOUNCEMENT_REMOVED_ACTION =
    "queuing/ANNOUNCEMENT_REMOVED_ACTION";

export const QUEUE_REMOVED_ACTION = "queuing/QUEUE_REMOVED_ACTION";

export const DEQUEUE_SELF_REQUESTED_ACTION =
    "queueing/DEQUEUE_SELF_REQUESTED_ACTION";

export const RESET_REMINDER_ACTION = "queuing/RESET_REMINDER_ACTION";

export const RESET_NEW_ANNOUNCEMENT_ACTION =
    "queuing/RESET_NEW_ANNOUNCEMENT_ACTION";

export const ACCEPT_NEXT_ACTION = "queuing/ACCEPT_NEXT_ACTION";

export const ROOM_QUEUE_LENGTHS_REQUESTED_ACTION =
    "queuing/ROOM_QUEUE_LENGTHS_REQUESTED_ACTION";
export const ROOM_QUEUE_LENGTHS_REQUEST_SUCCEEDED_ACTION =
    "queuing/ROOM_QUEUE_LENGTHS_REQUEST_SUCCEEDED_ACTION";
