export const PARTICIPANTS_FETCH_REQUESTED_ACTION =
    "participants/PARTICIPANTS_FETCH_REQUESTED_ACTION";

export const PARTICIPANTS_FETCH_REQUEST_SUCCEEDED_ACTION =
    "participants/PARTICIPANTS_FETCH_REQUEST_SUCCEEDED_ACTION";

export const COURSE_PARTICIPANTS_FETCH_REQUESTED_ACTION =
    "participants/COURSE_PARTICIPANTS_FETCH_REQUESTED_ACTION";

export const COURSE_PARTICIPANTS_FETCH_REQUEST_SUCCEEDED_ACTION =
    "participants/COURSE_PARTICIPANTS_FETCH_REQUEST_SUCCEEDED_ACTION";

export const COURSE_STAFF_PARTICIPANTS_FETCH_REQUESTED_ACTION =
    "participants/COURSE_STAFF_PARTICIPANTS_FETCH_REQUESTED_ACTION";

export const COURSE_STAFF_PARTICIPANTS_FETCH_REQUEST_SUCCEEDED_ACTION =
    "participants/COURSE_STAFF_PARTICIPANTS_FETCH_REQUEST_SUCCEEDED_ACTION";
