export const STUDENT_DASHBOARD_DATA_REQUESTED_ACTION =
    "student-dashboard/STUDENT_DASHBOARD_DATA_REQUESTED_ACTION";
export const STUDENT_DASHBOARD_DATA_REQUEST_SUCCEEDED_ACTION =
    "student-dashboard/STUDENT_DASHBOARD_DATA_REQUEST_SUCCEEDED_ACTION";
