export const ROOMS_FETCH_REQUESTED_ACTION =
    "rooms/ROOMS_FETCH_REQUESTED_ACTION";
export const ROOMS_FETCH_REQUEST_SUCCEEDED_ACTION =
    "rooms/ROOMS_FETCH_REQUEST_SUCCEEDED_ACTION";

export const ROOM_OPEN_REQUESTED_ACTION = "rooms/ROOM_OPEN_REQUESTED_ACTION";
export const ROOM_OPEN_REQUEST_SUCCEEDED_ACTION =
    "rooms/ROOM_OPEN_REQUEST_SUCCEEDED_ACTION";

export const ROOM_CLOSE_REQUESTED_ACTION = "rooms/ROOM_CLOSE_REQUESTED_ACTION";
export const ROOM_CLOSE_REQUEST_SUCCEEDED_ACTION =
    "rooms/ROOM_CLOSE_REQUEST_SUCCEEDED_ACTION";
