export const COMMENT_THREAD_CREATE_REQUESTED_ACTION = "comments/COMMENT_THREAD_CREATE_REQUESTED_ACTION";
export const COMMENT_THREAD_CREATE_REQUEST_SUCCEEDED_ACTION = "comments/COMMENT_THREAD_CREATE_REQUEST_SUCCEEDED_ACTION";

export const COMMENT_THREADS_REQUESTED_ACTION = "comments/COMMENT_THREADS_REQUESTED_ACTION";
export const COMMENT_THREADS_REQUEST_SUCCEEDED_ACTION = "comments/COMMENT_THREADS_REQUEST_SUCCEEDED_ACTION";

export const COMMENT_THREAD_REQUESTED_ACTION = "comments/COMMENT_THREAD_REQUESTED_ACTION";
export const COMMENT_THREAD_REQUEST_SUCCEEDED_ACTION = "comments/COMMENT_THREAD_REQUEST_SUCCEEDED_ACTION";

export const COMMENT_CREATE_REQUESTED_ACTION = "comments/COMMENT_CREATE_REQUESTED_ACTION";
export const COMMENT_CREATE_REQUEST_SUCCEEDED_ACTION = "comments/COMMENT_CREATE_REQUEST_SUCCEEDED_ACTION";

export const COMMENT_UPDATE_REQUESTED_ACTION = "comments/COMMENT_UPDATE_REQUESTED_ACTION";
export const COMMENT_UPDATE_REQUEST_SUCCEEDED_ACTION = "comments/COMMENT_UPDATE_REQUEST_SUCCEEDED_ACTION";

export const COMMENT_DELETE_REQUESTED_ACTION = "comments/COMMENT_DELETE_REQUESTED_ACTION";
export const COMMENT_DELETE_REQUEST_SUCCEEDED_ACTION = "comments/COMMENT_DELETE_REQUEST_SUCCEEDED_ACTION";
