export const JOBS_FETCH_REQUESTED_ACTION = "jobs/JOBS_FETCH_REQUESTED_ACTION";
export const JOBS_FETCH_REQUEST_SUCCEEDED_ACTION =
    "jobs/JOBS_FETCH_REQUEST_SUCCEEDED_ACTION";

export const JOB_ID_FETCH_REQUESTED_ACTION =
    "jobs/JOB_ID_FETCH_REQUESTED_ACTION";
export const JOB_ID_FETCH_REQUEST_SUCCEEDED_ACTION =
    "jobs/JOB_ID_FETCH_REQUEST_SUCCEEDED_ACTION";

export const JOB_REMOVE_REQUESTED_ACTION = "jobs/JOB_REMOVE_REQUESTED_ACTION";
export const JOB_REMOVE_REQUEST_SUCCEEDED_ACTION =
    "jobs/JOB_REMOVE_REQUEST_SUCCEEDED_ACTION";

export const JOB_ADD_ACTION = "jobs/JOB_ADD";
